site_name: Shiru ka
site_url: https://shiruka.github.io/
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: assets/SHIRUKA.png
  palette:
    primary: blue
plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        tr: türkçe
