site_name: Shiru ka
site_url: https://shiruka.github.io/
theme:
  name: readthedocs
  locale: en
nav:
  - Home: index.md
plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        tr: türkçe
