site_name: Shiru ka
site_url: https://shiruka.github.io/
repo_url: https://github.com/shiruka/shiruka/
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  palette:
    primary: blue
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        tr: Türkçe
