name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-static-i18n

      - run: |
          git pull
          mkdocs gh-deploy
